use_frameworks!

platform :ios, '9.0'

target 'AntiySoaTest_Example' do
  pod 'AntiySoaTest', :path => '../'

  target 'AntiySoaTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
